"""updated bid schema

Revision ID: 0e5adc9d06cf
Revises: f5c360194f72
Create Date: 2025-08-22 11:13:55.427978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5adc9d06cf'
down_revision: Union[str, Sequence[str], None] = 'f5c360194f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'member_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'member_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
