"""updated keys

Revision ID: b55fe857b8a9
Revises: 82c715396cdb
Create Date: 2025-08-13 15:40:38.173315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55fe857b8a9'
down_revision: Union[str, Sequence[str], None] = '82c715396cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_team_created_by_id', 'teams', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_team_sub_admin_id', 'teams', 'users', ['sub_admin_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_user_team_id', 'users', 'teams', ['team_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_team_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_team_sub_admin_id', 'teams', type_='foreignkey')
    op.drop_constraint('fk_team_created_by_id', 'teams', type_='foreignkey')
    # ### end Alembic commands ###
