"""Update BID table

Revision ID: f5c360194f72
Revises: 27f796f445be
Create Date: 2025-08-21 22:11:15.888688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c360194f72'
down_revision: Union[str, Sequence[str], None] = '27f796f445be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'team_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'team_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
