"""update

Revision ID: fac6b3c43da4
Revises: 58938835f95c
Create Date: 2025-08-28 16:16:38.805090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac6b3c43da4'
down_revision: Union[str, Sequence[str], None] = '58938835f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_team_created_by_id', 'teams', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_team_sub_admin_id', 'teams', 'users', ['sub_admin_id'], ['id'], use_alter=True)
    op.drop_constraint('user_sessions_refresh_token_key', 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'refresh_token')
    op.create_foreign_key('fk_user_team_id', 'users', 'teams', ['team_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_team_id', 'users', type_='foreignkey')
    op.add_column('user_sessions', sa.Column('refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_sessions_refresh_token_key', 'user_sessions', ['refresh_token'])
    op.drop_constraint('fk_team_sub_admin_id', 'teams', type_='foreignkey')
    op.drop_constraint('fk_team_created_by_id', 'teams', type_='foreignkey')
    # ### end Alembic commands ###
